config/routes.rb
Rails.application.routes.draw do
  resources :studios do
    resources :projects
  end

  devise_for :users
  root 'studios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :studio
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :studio
  mount_uploader :image, ImageUploader
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :user
  has_many :projects
  has_many :cities
  mount_uploader :logo, LogoUploader

  # scope :more_than_min_price, ->(min_price) { where("min_budget > ?", min_price) }
  # scope :less_than_max_price, ->(max_price) { where("created_at < ?", max_price) }
  # scope :selected_city, ->(city) { where("city == ?", city) }

  BUDGETS = [
    ['$3000 and under', 1],
    ['$3000-$10000', 2],
    ['$10,000-$25,000', 3],
    ['$25,000 - $50,000', 4],
    ['Over $50,000', 5]
  ].freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :email, :password, :password_confirmation, :remember_me, :username
  validates_presence_of :username

  has_many :studios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_studio
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = @studio.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = @studio.projects.new(project_params)
    if @studio.payed == false && @studio.projects.count >= 1
      flash[:notice] = 'You already have one free project.'
    else
      respond_to do |format|
        if @project.save
          format.html { redirect_to studio_path(@studio), notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end

   end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def set_studio
    @studio = current_user.studios.find(params[:studio_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :industry, :platform, :project_type, :technology, :image)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :filter]

  def index
    @studios = Studio.all
    @studios = @studios.where(budget: params[:budget]) if params[:budget].present?
    @studios = @studios.where(city: params[:city]) if params[:city].present?
    @studios = @studios.order(payed: :desc)
  end

  def show
  end

  def new
    @studio = current_user.studios.build
  end

  def edit
  end

  def create
    @studio = current_user.studios.build(studio_params)

    respond_to do |format|
      if @studio.save
        format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
        format.json { render :show, status: :created, location: @studio }
      else
        format.html { render :new }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @studio.update(studio_params)
        format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
        format.json { render :show, status: :ok, location: @studio }
      else
        format.html { render :edit }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @studio.destroy
    respond_to do |format|
      format.html { redirect_to studios_url, notice: 'Studio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_studio
    @studio = Studio.find(params[:id])
  end

  def studio_params
    params.require(:studio).permit(:name, :city, :budget, :logo, :technologies, :payed, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation" style="background-color:#404040;color:white;">
  <div class="container">
    <div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li id="white_link"><%= link_to 'Add studio', new_studio_path %></li>
          <li id="white_link"><%= link_to 'Account', edit_user_registration_path %></li>
          <li id="white_link"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li id="white_link"><%= link_to "Login", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
<div id = "budg_and_city" >
 <img src="/sortfolio2.png" id="img_logo">
Showing web designers in
<div class="dropdown" style="display: inline; color: #42b6ff">
  <text class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <b style="text-decoration: underline;">any city</b>
    <span class="caret"></span>
  </text>
  <ul class="dropdown-menu" >
    <% @cities = Studio.all.select(:city).uniq %>
    <% @cities.each do |studio| %>
    <li><a href="?city=<%=studio.city%>"> <%= studio.city %></a></li>
    <% end %>
    <li><a href="?city">Any city</a></li>
  </ul>
</div >

who work on projects for

<div class="dropdown" style="display: inline; color: #42b6ff">
  <text class=" dropdown-toggle"  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <b style="text-decoration: underline;">any budget</b>
    <span class="caret"></span>
  </text>
  <ul class="dropdown-menu" >
    <li><a href="?budget">any budget</a></li>
    <li><a href="?budget=1">$3,000 and under</a></li>
    <li><a href="?budget=2">$3,000-$10,000</a></li>
    <li><a href="?budget=3">$10,000-$25,000</a></li>
    <li><a href="?budget=4">$25,000-$50,000</a></li>
    <li><a href="?budget=5">Over $50,000</a></li>
  </ul>
</div>

    </div><!-- /.navbar-collapse -->
</div>
</div>
  </div><!-- /.container-fluid -->
  <div id = "phrase">
   <b> Find the right web designer for your next project.</b>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container" id="main_area">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

    <%= yield %>
  </div>
    <footer id="footer">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; Ilya Tsynenko 2016 </p>
        </div>
      </div>
    </footer>  
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, url: studio_projects_path(@studio), html: { multipart: true } do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>

  <div class="field">
    <%= f.label :platform %>
    <%= f.text_field :platform %>
  </div>

  <div class="field">
    <%= f.label :project_type %>
    <%= f.text_field :project_type %>
  </div>

  <div class="field">
    <%= f.label :technology %>
    <%= f.text_field :technology %>
  </div>

  <div class="image">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Industry</th>
      <th>Platform</th>
      <th>Type</th>
      <th>Technology</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.industry %></td>
        <td><%= project.platform %></td>
        <td><%= project.type %></td>
        <td><%= project.technology %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<p id="notice"><%= notice %></p>
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @project.industry %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @project.platform %>
</p>

<p>
  <strong>Type:</strong>
  <%= @project.project_type %>
</p>

<p>
  <strong>Technology:</strong>
  <%= @project.technology %>
</p>

<p>
  <%= image_tag @project.image.url(:large) %>
</p>


<%= link_to 'Edit', edit_studio_project_path(@project) %> |
<%= link_to 'Back', studio_path(@studio) %> 

app/views/studios/_form.html.erb
<%= simple_form_for @studio, html: { multipart: true } do |f| %>
  <% if studio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>
      <ul>
      <% studio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.input :name, label: 'Name' %>
  </p>
  <p>
    <%= f.input :city, label: 'City'  %>
  </p>
  <p>
    <%= f.select :budget, Studio::BUDGETS %>
  </p>
  <p>

    <%= f.input :logo, as: :file, label: 'Logo' %>
  </p>
  <p>

    <%= f.input :description, label: 'Description' %>
  </p>
  <p>
    <%= f.input :payed, as: :boolean, checked_value: true, unchecked_value: false%>

  </p>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/studios/edit.html.erb
<h1>Editing Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Show', @studio %> |
<%= link_to 'Back', studios_path %>

app/views/studios/index.html.erb
<div class="row">
  <div class="col-md-6 portfolio-item">
<% @studios.each do |studio| %>

<div class="container_slider">
  <ul id="slider">
          <div>
          <div id="budget_and_city">
          <%= studio.city %>     
          <p><%= Studio::BUDGETS[studio.budget].first %>
          </div>

          <div id="logo">

            <%if studio.logo%>
            <%= link_to (image_tag studio.logo_url(:thumb), class: 'image'), studio_path(studio.id)%>
            <%end%>

          </div>
        </div>

<% studio.projects.each do |project| %>  
  
  <% if studio.payed %>
    <li><%= link_to (image_tag project.image_url(:medium), class: 'image'), studio_path(project.studio_id) %></li>
    <% else %>
      <%= link_to (image_tag project.image_url(:thumb), class: 'image'), studio_path(project.studio_id) %>
  <% end %>

  </ul>

  <ul id="dots">   
    <li class="active"></li>
    <% num_of_dots = studio.projects.count-1 %>
    
    <% num_of_dots.times  do %>
    <li></li>
    <% end %>

  </ul>

  <button id="prev">Prev</button>
  <button id="next">Next</button>
<% end %>

 <% end %> 

 </div>
</div>

app/views/studios/new.html.erb
<h1>New Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Back', studios_path %>

app/views/studios/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= image_tag @studio.logo_url(:thumb) if @studio.logo.present? %></p>

<p>
  Typical budget: <b><%= Studio::BUDGETS[@studio.budget].first %></b> 
<p>
  Headquartered in <b style="text-decoration: underline;"><%= @studio.city %></b>
<p>
  <%= @studio.description %>
<p>
<% @studio.projects.each do |project| %>
  <tr>
  	<% if project.image.present? %>
    <td><%= link_to (image_tag project.image.url(:large)) , studio_project_path(project.studio_id, project.id) %></td><p>
    <% end %>
    <td><%= project.title %></td>
    <td><%= link_to "show", studio_project_path(project.studio_id, project.id) %></td><p>
  </tr>
<% end %>

<p><%= link_to "Add project", new_studio_project_path(@studio.id) %>
<p>
<%= link_to 'Edit', edit_studio_path(@studio) %> |
<%= link_to 'Back', studios_path %>